### ISSUE TITLE
Timeshift keymap

### ISSUE THREAD

**Issue by popking159** [OpenSPA/dvbapp2#20]
Thanks for last good update for openspa , I ask If timeshift keymap can be modified to pause and play with the same button , now it starts with pause button and play with ok button , 
If spa timeshift installed , it alters the already present keymap , pause and play opens context menu to choose action , this requires too many clicks , so I suggest to remap timeshift to pause and play with the same button so one click to pause and one click to play.
Thanks in advance .

**Comment by norhap** [comment]
@popking159 to initiate timeshift use short press, then to swap PLAY/PAUSE use long press to toggle both.

https://github.com/OpenSPA/dvbapp2/commit/fc2d44035cc616b290465d431b0b548adcc9a5e3
